create_docs_paths: [
  'integrations/pytorch-lightning/Neptune-PyTorch-Lightning-basic.ipynb'
]

run_docs_paths:
  included_patterns: [
    '/docs',
    '/tests',
    '/showcase',
  ]
  excluded_patterns: [
    '/.ipynb_checkpoints',
    '/.git',
  ]
