name: pytorch_lightning 
on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '*/14 3 * * *' # Run once daily at arbitrary time at night
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install -r requirements.txt
      - run: python -m ci.test_lightning
